const mongoose = require('mongoose')
const FoodSchema = mongoose.Schema({
    
    name: String,
    usda_id: String,
    fat: Number,
    calories: Number,
    proteins: Number,
    carbohydrates: Number,
    serving: Number,
    nutrients: {
      Calcium: Number,
      Iron: Number,
      Potassium: Number,
      Magnesium: Number,
      Phosphorus: Number,
      Sodium: Number,
      Zinc: Number,
      Copper: Number,
      Manganese: Number,
      Selenium: Number,
      'Vitamin C': Number,
      'Vitamin B12': Number,
      'Vitamin B1': Number,
      'Vitamin B2': Number,
      'Vitamin B3': Number,
      'Vitamin B5': Number,
      'Vitamin B6': Number,
      'Vitamin B7': Number,
      'Vitamin B9': Number,
      Choline: Number,
      'Vitamin A': Number,
      'Vitamin E': Number,
      'Linoleic acid': Number,
      'α-Linolenic acid': Number,
      Tryptophan: Number,
      Threonine: Number,
      Isoleucine: Number,
      Leucine: Number,
      Lysine: Number,
      Methionine: Number,
      Phenylalanine: Number,
      Valine: Number,
      Histidine: Number,
    },
});

module.exports = mongoose.model('Foods', FoodSchema)